### ISSUE TITLE
Fluid Filters don't work and cause NPE crash

### ISSUE THREAD

**Issue by TheIllusiveC4** [WayofTime/BloodMagic#1286]
#### Issue Description:
Fluid filters do not transfer fluids between nodes. Placing chests next to a node with a fluid filter will cause an NPE crash.

#### What happens:
Placing an input routing node over a blood tank with water and installing a fluid filter set to filter a blood tank with water does not transfer the water over to an output routing node over a blood tank set to the same filter settings. Placing a chest next to the input routing node (haven't tested if it behaves differently for the output routing node) causes an NPE crash in the Master Routing Node tile entity that breaks the world unless a backup is restored from before this happens.

Crash log: https://pastebin.com/5mVG7tr9

#### What you expected to happen:
The fluid filters will transfer the water between blood tanks over the routing network. Placing a chest next to a fluid filtered node does not cause a crash.

#### Steps to reproduce:

1. Place two tier 1 blood tanks
2. Fill up one blood tank with water (I only filled it with one bucket of water)
3. Place an input routing node over the blood tank with water
4. Place an output routing node over the blood tank without water
5. Link both of those nodes to a master routing node
6. Place fluid filters in both nodes
7. Set both fluid filters to filter a blood tank with 1000 MB of water stored
8. Nothing happens - first issue
9. Place a wooden chest next to the input routing node
10. Crash to desktop - second issue

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.12.2-2.2.11-96
- Minecraft: 1.12.2
- Forge: 14.23.3.2673

**Comment by TehNut** [comment]
I don't know if that commit fixes it not working, but it should fix the crash.

**Comment by TheIllusiveC4** [comment]
That does indeed fix the crash, but it seems like the output map needs to be changed as well since I found out that is also crashing.
https://github.com/WayofTime/BloodMagic/blob/809e37b151db18563dcb2679a6d3195eb02560a1/src/main/java/WayofTime/bloodmagic/tile/routing/TileMasterRoutingNode.java#L101

**Comment by TehNut** [comment]
👍

**Comment by TheIllusiveC4** [comment]
Yep, no more crashes. Thanks!
I had hoped that would incidentally also fix the fluid filters not working, but unfortunately that's still an issue.

**Comment by TehNut** [comment]
I'll leave that to Way. I don't exactly know how to the routing system works.
